gcc -o exec main/main.c resources/log.c -Wall -lpthread
#CC=gcc
#CFLAGS=(-Wall -lpthread -DLOG_USE_COLOR)
#EXEC=main

#prefix=./
#bindir=($prefix)/bin
#files=main/main.c resources/log.c

#@echo "Starting project compilation..."
#$(CC) -o $(EXEC) main/main.c resources/log.c $(CFLAGS)
#@mv $(EXEC) $(bindir)/
#@echo "Project compiled with success"
